apiVersion: v1
kind: Service
metadata:
  name: texhive-service
  namespace: texhive
spec:
  selector:
    app: texhive
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
