apiVersion: apps/v1
kind: Deployment
metadata:
  name: humanize-service
  namespace: texhive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: humanize-service
  template:
    metadata:
      labels:
        app: humanize-service
    spec:
      containers:
        - name: humanize-service
          image: ajratnam/humanize-service:latest
          ports:
            - containerPort: 8003