apiVersion: v1
kind: Service
metadata:
  name: humanize-service
  namespace: texhive
spec:
  selector:
    app: humanize-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP