services:
  texhive:
    image: ajratnam/texhive:latest
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - POETRY_VIRTUALENVS_IN_PROJECT=true
    volumes:
      - ./data:/app/data
      - ./temp:/app/temp
    networks:
      - texhive-net

  ref-service:
    image: ajratnam/ref-service:latest
    build:
      context: ./microservices/code_ref
    ports:
      - "8001:8001"
    networks:
      - texhive-net

  compile-service:
    image: ajratnam/compile-service:latest
    build:
      context: ./microservices/latex_compiler
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data
      - ./temp:/app/temp
    networks:
      - texhive-net

  humanize-service:
    image: ajratnam/humanize-service:latest # nishithp/humanize-service:latest
    build: 
      context: ./microservices/humanize-service
    ports:
      - "8003:8003"
    networks:
      - texhive-net

networks:
  texhive-net:
    driver: bridge
