---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: texhive
---
# Texhive Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: texhive
  namespace: texhive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: texhive
  template:
    metadata:
      labels:
        app: texhive
    spec:
      containers:
        - name: texhive
          image: ajratnam/texhive:latest
          ports:
            - containerPort: 8000
          env:
            - name: POETRY_VIRTUALENVS_IN_PROJECT
              value: "true"
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: temp-volume
              mountPath: /app/temp
            - name: routes-secret
              mountPath: /app/routes/credentials.json
              subPath: credentials.json
              readOnly: true
      volumes:
        - name: data-volume
          hostPath:
            path: /data
            type: DirectoryOrCreate
        - name: temp-volume
          hostPath:
            path: /temp
            type: DirectoryOrCreate
        - name: routes-secret
          secret:
            secretName: my-creds

---
# Texhive Service
apiVersion: v1
kind: Service
metadata:
  name: texhive-service
  namespace: texhive
spec:
  selector:
    app: texhive
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
---
# Ref Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ref-service
  namespace: texhive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ref-service
  template:
    metadata:
      labels:
        app: ref-service
    spec:
      containers:
        - name: ref-service
          image: ajratnam/ref-service:latest
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          
---
# Ref Service Service
apiVersion: v1
kind: Service
metadata:
  name: ref-service
  namespace: texhive
spec:
  selector:
    app: ref-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
# Compile Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compile-service
  namespace: texhive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compile-service
  template:
    metadata:
      labels:
        app: compile-service
    spec:
      containers:
        - name: compile-service
          image: ajratnam/compile-service:latest
          ports:
            - containerPort: 8002
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: temp-volume
              mountPath: /app/temp
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
      volumes:
        - name: data-volume
          hostPath:
            path: /data
            type: DirectoryOrCreate
        - name: temp-volume
          hostPath:
            path: /temp
            type: DirectoryOrCreate
---
# Compile Service Service
apiVersion: v1
kind: Service
metadata:
  name: compile-service
  namespace: texhive
spec:
  selector:
    app: compile-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
---
# Humanize Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: humanize-service
  namespace: texhive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humanize-service
  template:
    metadata:
      labels:
        app: humanize-service
    spec:
      containers:
        - name: humanize-service
          image: ajratnam/humanize-service:latest
          ports:
            - containerPort: 8003
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
---
# Humanize Service Service
apiVersion: v1
kind: Service
metadata:
  name: humanize-service
  namespace: texhive
spec:
  selector:
    app: humanize-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP
---
# Autoscaler texhive
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: texhive-hpa
  namespace: texhive
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: texhive
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
# Autoscaler ref-service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ref-service-hpa
  namespace: texhive
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ref-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
# Autoscaler compile-service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: compile-service-hpa
  namespace: texhive
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: compile-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
# Autoscaler humanize-service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: humanize-service-hpa
  namespace: texhive
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: humanize-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50