apiVersion: apps/v1
kind: Deployment
metadata:
  name: compile-service
  namespace: texhive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: compile-service
  template:
    metadata:
      labels:
        app: compile-service
    spec:
      containers:
        - name: compile-service
          image: ajratnam/compile-service:latest
          ports:
            - containerPort: 8002
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: temp-volume
              mountPath: /app/temp
      volumes:
        - name: data-volume
          hostPath:
            path: /data
            type: DirectoryOrCreate
        - name: temp-volume
          hostPath:
            path: /temp
            type: DirectoryOrCreate