apiVersion: v1
kind: Service
metadata:
  name: compile-service
  namespace: texhive
spec:
  selector:
    app: compile-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP