apiVersion: v1
kind: Service
metadata:
  name: ref-service
  namespace: texhive
spec:
  selector:
    app: ref-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
